--------------------------------------------------------
--  File created - Monday-May-18-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_SN_PACIENTE
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_PACIENTE" 
   (	"ID_PACIENTE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME_PACIENTE" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"SENHA" VARCHAR2(255 BYTE), 
	"CPF" VARCHAR2(14 BYTE), 
	"TIPO_PERFIL" VARCHAR2(20 BYTE) DEFAULT 'paciente', 
	"DATA_NASCIMENTO" DATE, 
	"GENERO" VARCHAR2(30 BYTE), 
	"PAIS" VARCHAR2(100 BYTE), 
	"CIDADE" VARCHAR2(100 BYTE), 
	"RENDA_SALARIO_MINIMO" NUMBER(6,2), 
	"DESCRICAO_PROBLEMA" VARCHAR2(2000 BYTE), 
	"TIPO_DOR" VARCHAR2(100 BYTE), 
	"TEMPO_DOR_DIAS" NUMBER(5,0) DEFAULT 0, 
	"URGENCIA" VARCHAR2(50 BYTE), 
	"CRIADO_EM" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"ESTADO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SN_OFERTA_SLOT
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_OFERTA_SLOT" 
   (	"ID_SLOT" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_OFERTA" NUMBER, 
	"DATA_SLOT" VARCHAR2(10 BYTE), 
	"HORA_SLOT" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SN_OFERTA
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_OFERTA" 
   (	"ID_OFERTA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_DENTISTA" NUMBER, 
	"ID_PACIENTE" NUMBER, 
	"PROCEDIMENTO" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'pendente', 
	"SLOT_DATA" VARCHAR2(10 BYTE), 
	"SLOT_HORA" VARCHAR2(5 BYTE), 
	"CRIADO_EM" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SN_MENSAGEM_SITE
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_MENSAGEM_SITE" 
   (	"ID_MENSAGEM" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"ASSUNTO" VARCHAR2(300 BYTE), 
	"MENSAGEM" VARCHAR2(4000 BYTE), 
	"DATA_ENVIO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SN_MATCH
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_MATCH" 
   (	"ID_MATCH" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DATA_SOLICITACAO" TIMESTAMP (6), 
	"DATA_AGENDADA" TIMESTAMP (6), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'PENDENTE', 
	"SCORE_MATCH" NUMBER(6,3), 
	"PRIORIDADE" NUMBER(6,3), 
	"OBSERVACAO" VARCHAR2(2000 BYTE), 
	"CRIADO_EM" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ID_PACIENTE" NUMBER, 
	"ID_ESPECIALIDADE" NUMBER, 
	"ID_DENTISTA" NUMBER, 
	"ID_AVALIACAO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SN_ESPECIALIDADE
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_ESPECIALIDADE" 
   (	"ID_ESPECIALIDADE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME_ESPECIALIDADE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SN_DISPONIBILIDADE_DENTISTA
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA" 
   (	"ID_DISPONIBILIDADE" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"HORARIO_INICIO" TIMESTAMP (6), 
	"HORARIO_FIM" TIMESTAMP (6), 
	"OBSERVACAO" VARCHAR2(500 BYTE), 
	"DIA_SEMANA" VARCHAR2(50 BYTE), 
	"ID_DENTISTA" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBSPC_ALUNOS" ;

   COMMENT ON COLUMN "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA"."HORARIO_INICIO" IS 'Horário de início do período disponível.';
   COMMENT ON COLUMN "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA"."HORARIO_FIM" IS 'Horário de fim. Deve ser posterior ao início.';
   COMMENT ON COLUMN "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA"."DIA_SEMANA" IS 'Dia da semana: SEGUNDA a DOMINGO.';
   COMMENT ON TABLE "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA"  IS 'Registra os horários de disponibilidade de cada dentista voluntário.';
--------------------------------------------------------
--  DDL for Table T_SN_DENTISTA_ESPECIALIDADE
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_DENTISTA_ESPECIALIDADE" 
   (	"ID_DENTISTA" NUMBER(*,0), 
	"ID_ESPECIALIDADE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBSPC_ALUNOS" ;

   COMMENT ON TABLE "RM567980"."T_SN_DENTISTA_ESPECIALIDADE"  IS 'Tabela associativa que relaciona dentistas às suas especialidades (N:N).';
--------------------------------------------------------
--  DDL for Table T_SN_DENTISTA
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_DENTISTA" 
   (	"ID_DENTISTA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME_DENTISTA" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"SENHA" VARCHAR2(255 BYTE), 
	"CRO" VARCHAR2(20 BYTE), 
	"TIPO_PERFIL" VARCHAR2(20 BYTE) DEFAULT 'dentista', 
	"MAX_PACIENTES_MES" NUMBER(4,0) DEFAULT 10, 
	"ATENDIDOS_MES" NUMBER(4,0) DEFAULT 0, 
	"PAIS" VARCHAR2(100 BYTE), 
	"CIDADE" VARCHAR2(100 BYTE), 
	"DESCRICAO_CLINICA" VARCHAR2(2000 BYTE), 
	"CRIADO_EM" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"ESTADO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SN_CONTATO
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_CONTATO" 
   (	"ID_CONTATO" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TIPO_CONTATO" VARCHAR2(50 BYTE), 
	"CONTATO" VARCHAR2(255 BYTE), 
	"ID_PACIENTE" NUMBER(*,0), 
	"ID_DENTISTA" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBSPC_ALUNOS" ;

   COMMENT ON COLUMN "RM567980"."T_SN_CONTATO"."TIPO_CONTATO" IS 'Tipo do contato: TELEFONE, EMAIL ou WHATSAPP.';
   COMMENT ON TABLE "RM567980"."T_SN_CONTATO"  IS 'Armazena os contatos (telefone, e-mail, WhatsApp) de pacientes e dentistas.';
--------------------------------------------------------
--  DDL for Table T_SN_AVALIACAO
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_AVALIACAO" 
   (	"ID_AVALIACAO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOTA_PACIENTE_PARA_DENTISTA" NUMBER(4,1), 
	"COMENTARIO_PACIENTE" VARCHAR2(1000 BYTE), 
	"CRIADO_EM" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table T_SN_ATENDIMENTO
--------------------------------------------------------

  CREATE TABLE "RM567980"."T_SN_ATENDIMENTO" 
   (	"ID_ATENDIMENTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DATA_INICIO" TIMESTAMP (6), 
	"PROCEDIMENTO_REALIZADO" VARCHAR2(500 BYTE), 
	"DIAGNOSTICO_FINAL" VARCHAR2(2000 BYTE), 
	"OBSERVACAO_CLINICA" VARCHAR2(2000 BYTE), 
	"STATUS_ATENDIMENTO" VARCHAR2(20 BYTE) DEFAULT 'EM_ANDAMENTO', 
	"ENCAMINHAMENTO" VARCHAR2(500 BYTE), 
	"ID_MATCH" NUMBER, 
	"ID_DENTISTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index IDX_PACIENTE_CIDADE
--------------------------------------------------------

  CREATE INDEX "RM567980"."IDX_PACIENTE_CIDADE" ON "RM567980"."T_SN_PACIENTE" ("CIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703643
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703643" ON "RM567980"."T_SN_PACIENTE" ("ID_PACIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703644
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703644" ON "RM567980"."T_SN_PACIENTE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703645
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703645" ON "RM567980"."T_SN_PACIENTE" ("CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006725455
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006725455" ON "RM567980"."T_SN_OFERTA_SLOT" ("ID_SLOT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006725448
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006725448" ON "RM567980"."T_SN_OFERTA" ("ID_OFERTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703686
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703686" ON "RM567980"."T_SN_MENSAGEM_SITE" ("ID_MENSAGEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index IDX_MATCH_PACIENTE
--------------------------------------------------------

  CREATE INDEX "RM567980"."IDX_MATCH_PACIENTE" ON "RM567980"."T_SN_MATCH" ("ID_PACIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index IDX_MATCH_DENTISTA
--------------------------------------------------------

  CREATE INDEX "RM567980"."IDX_MATCH_DENTISTA" ON "RM567980"."T_SN_MATCH" ("ID_DENTISTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703667
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703667" ON "RM567980"."T_SN_MATCH" ("ID_MATCH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703630
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703630" ON "RM567980"."T_SN_ESPECIALIDADE" ("ID_ESPECIALIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006684077
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006684077" ON "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA" ("ID_DISPONIBILIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index PK_DENT_ESP
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."PK_DENT_ESP" ON "RM567980"."T_SN_DENTISTA_ESPECIALIDADE" ("ID_DENTISTA", "ID_ESPECIALIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703657
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703657" ON "RM567980"."T_SN_DENTISTA" ("ID_DENTISTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703658
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703658" ON "RM567980"."T_SN_DENTISTA" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703659
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703659" ON "RM567980"."T_SN_DENTISTA" ("CRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006684081
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006684081" ON "RM567980"."T_SN_CONTATO" ("ID_CONTATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index UK_CONTATO_PACIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."UK_CONTATO_PACIENTE" ON "RM567980"."T_SN_CONTATO" ("CONTATO", "ID_PACIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703635
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703635" ON "RM567980"."T_SN_AVALIACAO" ("ID_AVALIACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index IDX_ATEND_MATCH
--------------------------------------------------------

  CREATE INDEX "RM567980"."IDX_ATEND_MATCH" ON "RM567980"."T_SN_ATENDIMENTO" ("ID_MATCH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index IDX_ATEND_DENTISTA
--------------------------------------------------------

  CREATE INDEX "RM567980"."IDX_ATEND_DENTISTA" ON "RM567980"."T_SN_ATENDIMENTO" ("ID_DENTISTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006703677
--------------------------------------------------------

  CREATE UNIQUE INDEX "RM567980"."SYS_C006703677" ON "RM567980"."T_SN_ATENDIMENTO" ("ID_ATENDIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  Constraints for Table T_SN_PACIENTE
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_PACIENTE" ADD CONSTRAINT "CK_URGENCIA" CHECK (URGENCIA IN ('ALTA','MEDIA','BAIXA')) ENABLE;
  ALTER TABLE "RM567980"."T_SN_PACIENTE" MODIFY ("ID_PACIENTE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_PACIENTE" MODIFY ("NOME_PACIENTE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_PACIENTE" MODIFY ("TIPO_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_PACIENTE" MODIFY ("PAIS" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_PACIENTE" MODIFY ("CIDADE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_PACIENTE" MODIFY ("CRIADO_EM" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_PACIENTE" ADD PRIMARY KEY ("ID_PACIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM567980"."T_SN_PACIENTE" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM567980"."T_SN_PACIENTE" ADD UNIQUE ("CPF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_OFERTA_SLOT
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_OFERTA_SLOT" MODIFY ("ID_SLOT" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_OFERTA_SLOT" MODIFY ("ID_OFERTA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_OFERTA_SLOT" MODIFY ("DATA_SLOT" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_OFERTA_SLOT" MODIFY ("HORA_SLOT" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_OFERTA_SLOT" ADD PRIMARY KEY ("ID_SLOT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_OFERTA
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_OFERTA" MODIFY ("ID_OFERTA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_OFERTA" MODIFY ("ID_DENTISTA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_OFERTA" MODIFY ("ID_PACIENTE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_OFERTA" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_OFERTA" ADD PRIMARY KEY ("ID_OFERTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_MENSAGEM_SITE
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_MENSAGEM_SITE" MODIFY ("ID_MENSAGEM" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MENSAGEM_SITE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MENSAGEM_SITE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MENSAGEM_SITE" MODIFY ("ASSUNTO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MENSAGEM_SITE" MODIFY ("MENSAGEM" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MENSAGEM_SITE" MODIFY ("DATA_ENVIO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MENSAGEM_SITE" ADD PRIMARY KEY ("ID_MENSAGEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_MATCH
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_MATCH" ADD CONSTRAINT "CK_MATCH_STATUS" CHECK (STATUS IN ('PENDENTE','CONFIRMADO','CONCLUIDO','CANCELADO')) ENABLE;
  ALTER TABLE "RM567980"."T_SN_MATCH" MODIFY ("ID_MATCH" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MATCH" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MATCH" MODIFY ("CRIADO_EM" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MATCH" MODIFY ("ID_PACIENTE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MATCH" MODIFY ("ID_ESPECIALIDADE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MATCH" MODIFY ("ID_DENTISTA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_MATCH" ADD PRIMARY KEY ("ID_MATCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_ESPECIALIDADE
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_ESPECIALIDADE" MODIFY ("ID_ESPECIALIDADE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_ESPECIALIDADE" MODIFY ("NOME_ESPECIALIDADE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_ESPECIALIDADE" ADD PRIMARY KEY ("ID_ESPECIALIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_DISPONIBILIDADE_DENTISTA
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA" ADD CONSTRAINT "CK_DISP_DIA_SEMANA" CHECK (dia_semana IN ('SEGUNDA','TERCA','QUARTA','QUINTA','SEXTA','SABADO','DOMINGO')) ENABLE;
  ALTER TABLE "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA" ADD CONSTRAINT "CK_DISP_HORARIO" CHECK (horario_fim > horario_inicio) ENABLE;
  ALTER TABLE "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA" MODIFY ("ID_DISPONIBILIDADE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA" MODIFY ("HORARIO_INICIO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA" MODIFY ("HORARIO_FIM" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA" MODIFY ("DIA_SEMANA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DISPONIBILIDADE_DENTISTA" ADD PRIMARY KEY ("ID_DISPONIBILIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_DENTISTA_ESPECIALIDADE
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_DENTISTA_ESPECIALIDADE" ADD CONSTRAINT "PK_DENT_ESP" PRIMARY KEY ("ID_DENTISTA", "ID_ESPECIALIDADE")
  USING INDEX "RM567980"."PK_DENT_ESP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_DENTISTA
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("ID_DENTISTA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("NOME_DENTISTA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("CRO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("TIPO_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("MAX_PACIENTES_MES" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("ATENDIDOS_MES" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("PAIS" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("CIDADE" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" MODIFY ("CRIADO_EM" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_DENTISTA" ADD PRIMARY KEY ("ID_DENTISTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM567980"."T_SN_DENTISTA" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM567980"."T_SN_DENTISTA" ADD UNIQUE ("CRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_CONTATO
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_CONTATO" ADD CONSTRAINT "CK_CONTATO_TIPO" CHECK (tipo_contato IN ('TELEFONE', 'EMAIL', 'WHATSAPP')) ENABLE;
  ALTER TABLE "RM567980"."T_SN_CONTATO" MODIFY ("ID_CONTATO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_CONTATO" MODIFY ("TIPO_CONTATO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_CONTATO" MODIFY ("CONTATO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_CONTATO" ADD PRIMARY KEY ("ID_CONTATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
  ALTER TABLE "RM567980"."T_SN_CONTATO" ADD CONSTRAINT "UK_CONTATO_PACIENTE" UNIQUE ("CONTATO", "ID_PACIENTE")
  USING INDEX "RM567980"."UK_CONTATO_PACIENTE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_AVALIACAO
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_AVALIACAO" ADD CONSTRAINT "CK_NOTA" CHECK (NOTA_PACIENTE_PARA_DENTISTA BETWEEN 0 AND 10) ENABLE;
  ALTER TABLE "RM567980"."T_SN_AVALIACAO" MODIFY ("ID_AVALIACAO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_AVALIACAO" MODIFY ("NOTA_PACIENTE_PARA_DENTISTA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_AVALIACAO" MODIFY ("CRIADO_EM" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_AVALIACAO" ADD PRIMARY KEY ("ID_AVALIACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_SN_ATENDIMENTO
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" ADD CONSTRAINT "CK_ATEND_STATUS" CHECK (STATUS_ATENDIMENTO IN ('EM_ANDAMENTO','CONCLUIDO','CANCELADO')) ENABLE;
  ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" MODIFY ("ID_ATENDIMENTO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" MODIFY ("STATUS_ATENDIMENTO" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" MODIFY ("ID_MATCH" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" MODIFY ("ID_DENTISTA" NOT NULL ENABLE);
  ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" ADD PRIMARY KEY ("ID_ATENDIMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SN_OFERTA_SLOT
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_OFERTA_SLOT" ADD CONSTRAINT "FK_SLOT_OFERTA" FOREIGN KEY ("ID_OFERTA")
	  REFERENCES "RM567980"."T_SN_OFERTA" ("ID_OFERTA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SN_OFERTA
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_OFERTA" ADD CONSTRAINT "FK_OFERTA_DENTISTA" FOREIGN KEY ("ID_DENTISTA")
	  REFERENCES "RM567980"."T_SN_DENTISTA" ("ID_DENTISTA") ENABLE;
  ALTER TABLE "RM567980"."T_SN_OFERTA" ADD CONSTRAINT "FK_OFERTA_PACIENTE" FOREIGN KEY ("ID_PACIENTE")
	  REFERENCES "RM567980"."T_SN_PACIENTE" ("ID_PACIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SN_MATCH
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_MATCH" ADD CONSTRAINT "FK_MATCH_AVALIACAO" FOREIGN KEY ("ID_AVALIACAO")
	  REFERENCES "RM567980"."T_SN_AVALIACAO" ("ID_AVALIACAO") ENABLE;
  ALTER TABLE "RM567980"."T_SN_MATCH" ADD CONSTRAINT "FK_MATCH_DENTISTA" FOREIGN KEY ("ID_DENTISTA")
	  REFERENCES "RM567980"."T_SN_DENTISTA" ("ID_DENTISTA") ENABLE;
  ALTER TABLE "RM567980"."T_SN_MATCH" ADD CONSTRAINT "FK_MATCH_ESPEC" FOREIGN KEY ("ID_ESPECIALIDADE")
	  REFERENCES "RM567980"."T_SN_ESPECIALIDADE" ("ID_ESPECIALIDADE") ENABLE;
  ALTER TABLE "RM567980"."T_SN_MATCH" ADD CONSTRAINT "FK_MATCH_PACIENTE" FOREIGN KEY ("ID_PACIENTE")
	  REFERENCES "RM567980"."T_SN_PACIENTE" ("ID_PACIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_SN_ATENDIMENTO
--------------------------------------------------------

  ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" ADD CONSTRAINT "FK_ATEND_DENTISTA" FOREIGN KEY ("ID_DENTISTA")
	  REFERENCES "RM567980"."T_SN_DENTISTA" ("ID_DENTISTA") ENABLE;
  ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" ADD CONSTRAINT "FK_ATEND_MATCH" FOREIGN KEY ("ID_MATCH")
	  REFERENCES "RM567980"."T_SN_MATCH" ("ID_MATCH") ENABLE;

--------------------------------------------------------
--  COMPLEMENTO — Colunas e tabelas usadas pelo backend
--  Execute este bloco APÓS o script principal acima
--------------------------------------------------------

-- ── TELEFONE em T_SN_PACIENTE (usado em PacienteDAO) ─────────────────────────
ALTER TABLE "RM567980"."T_SN_PACIENTE" ADD "TELEFONE" VARCHAR2(20 BYTE);

-- ── ID_DENTISTA_ADOTANTE em T_SN_PACIENTE (V2 migration) ─────────────────────
ALTER TABLE "RM567980"."T_SN_PACIENTE" ADD "ID_DENTISTA_ADOTANTE" NUMBER NULL;
ALTER TABLE "RM567980"."T_SN_PACIENTE" ADD CONSTRAINT "FK_PACIENTE_DENTISTA_ADOTANTE"
    FOREIGN KEY ("ID_DENTISTA_ADOTANTE")
    REFERENCES "RM567980"."T_SN_DENTISTA" ("ID_DENTISTA") ENABLE;

-- ── STATUS_ATIVO / INATIVADO_EM — soft delete (V1 migration) ─────────────────
ALTER TABLE "RM567980"."T_SN_PACIENTE"    ADD "STATUS_ATIVO" VARCHAR2(1) DEFAULT 'S' NOT NULL;
ALTER TABLE "RM567980"."T_SN_PACIENTE"    ADD CONSTRAINT "CK_PACIENTE_STATUS_ATIVO"    CHECK ("STATUS_ATIVO" IN ('S','N')) ENABLE;
ALTER TABLE "RM567980"."T_SN_PACIENTE"    ADD "INATIVADO_EM" TIMESTAMP NULL;

ALTER TABLE "RM567980"."T_SN_DENTISTA"    ADD "STATUS_ATIVO" VARCHAR2(1) DEFAULT 'S' NOT NULL;
ALTER TABLE "RM567980"."T_SN_DENTISTA"    ADD CONSTRAINT "CK_DENTISTA_STATUS_ATIVO"    CHECK ("STATUS_ATIVO" IN ('S','N')) ENABLE;
ALTER TABLE "RM567980"."T_SN_DENTISTA"    ADD "INATIVADO_EM" TIMESTAMP NULL;

ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" ADD "STATUS_ATIVO" VARCHAR2(1) DEFAULT 'S' NOT NULL;
ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" ADD CONSTRAINT "CK_ATENDIMENTO_STATUS_ATIVO" CHECK ("STATUS_ATIVO" IN ('S','N')) ENABLE;
ALTER TABLE "RM567980"."T_SN_ATENDIMENTO" ADD "INATIVADO_EM" TIMESTAMP NULL;

ALTER TABLE "RM567980"."T_SN_MATCH"       ADD "STATUS_ATIVO" VARCHAR2(1) DEFAULT 'S' NOT NULL;
ALTER TABLE "RM567980"."T_SN_MATCH"       ADD CONSTRAINT "CK_MATCH_STATUS_ATIVO"       CHECK ("STATUS_ATIVO" IN ('S','N')) ENABLE;
ALTER TABLE "RM567980"."T_SN_MATCH"       ADD "INATIVADO_EM" TIMESTAMP NULL;

ALTER TABLE "RM567980"."T_SN_OFERTA"      ADD "STATUS_ATIVO" VARCHAR2(1) DEFAULT 'S' NOT NULL;
ALTER TABLE "RM567980"."T_SN_OFERTA"      ADD CONSTRAINT "CK_OFERTA_STATUS_ATIVO"      CHECK ("STATUS_ATIVO" IN ('S','N')) ENABLE;
ALTER TABLE "RM567980"."T_SN_OFERTA"      ADD "INATIVADO_EM" TIMESTAMP NULL;

-- ── T_SN_HISTORICO (usada por HistoricoDAO) ───────────────────────────────────
CREATE TABLE "RM567980"."T_SN_HISTORICO" (
    "ID_HISTORICO"   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_PACIENTE"    NUMBER NOT NULL,
    "TITULO"         VARCHAR2(200 BYTE),
    "STATUS"         VARCHAR2(50 BYTE),
    "DATA_CONSULTA"  VARCHAR2(10 BYTE),
    "HORA_CONSULTA"  VARCHAR2(5 BYTE),
    "PROCEDIMENTO"   VARCHAR2(200 BYTE),
    "DENTISTA"       VARCHAR2(200 BYTE),
    CONSTRAINT "FK_HISTORICO_PACIENTE" FOREIGN KEY ("ID_PACIENTE")
        REFERENCES "RM567980"."T_SN_PACIENTE" ("ID_PACIENTE") ENABLE
);

COMMIT;
